Initial Commit and Requestor List table
Miyunecadz/registrar-record-management-system pull request #11
Opened 2023-10-08 15:25 UTC by cadz15

Ingani gajud ning git nga mag balik2 ang commits bisan nag na pr na?

2023-10-09 13:38 UTC, Miyunecadz commented
![image](https://github.com/Miyunecadz/registrar-record-management-system/assets/43285621/697cb1ed-fca1-4eb7-a571-e7b144565e5a)
In the view requestor information. Add required tag or indicator.

2023-10-09 13:38 UTC, Miyunecadz requested changes
![image](https://github.com/Miyunecadz/registrar-record-management-system/assets/43285621/ea5cba29-8127-439d-b714-4d9f0aa74ed3)
Add fields indicator

2023-10-12 14:23 UTC, cadz15 commented
Please review my updated PR. 

 new UI for;
 - Request list
 - Request Status with Timeline and Approve Form

2023-10-14 07:16 UTC, Miyunecadz approved these changes

2023-10-14 07:16 UTC, merged